name: fawkes
main: ivy.fawkes.Main
version: 0.0.9
depend: ["WorldGuard", "WorldEdit", "BetonQuest"]
commands:
  fks:
    description: 'Testing a clojure command.'
    usage: '/fks reloot'
    permission: fawkes.fks
    