name: fawkes
main: ivy.fawkes.loader.ClojurePlugin
version: 0.0.9
depend: ["WorldGuard", "WorldEdit", "BetonQuest","Votifier"]
commands:
  fkx:
    description: 'Play with classes.'
    usage: '/fkx'
    permissions: fawkes.fkx
  fkey:
    description: 'Give a player a crate key.'
    usage: '/fkey type player amount'
    permissions: fawkes.fkey
  fks:
    description: 'Testing a clojure command.'
    usage: '/fks reloot'
    permission: fawkes.fks
